/**
 * Workflow Automation System API TypeScript Definitions
 * 
 * Copy file này vào Frontend project của bạn:
 * - Next.js: types/workflow.ts
 * - React: src/types/workflow.ts
 * 
 * Base URL: http://localhost:3000 (development)
 * Authentication: Bearer token trong header Authorization
 */

// ============================================
// API Response Wrapper
// ============================================

export interface ApiResponse<T> {
  data?: T;
  error?: string;
  message?: string;
  code?: string;
}

// ============================================
// Core Workflow Types
// ============================================

export interface Workflow {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface WorkflowNode {
  id: string;
  type: NodeType;
  config: Record<string, any>;
  position?: { x: number; y: number };
  data?: Record<string, any>;
}

export interface WorkflowEdge {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string;
  targetHandle?: string;
}

export type NodeType =
  // Logic Nodes
  | 'if-else'
  | 'switch'
  | 'loop'
  | 'delay'
  | 'merge'
  | 'set-variable'
  | 'code'
  | 'data-mapper'
  // Action Nodes
  | 'send-email'
  | 'read-email'
  | 'ai-chat'
  | 'ai-classifier'
  | 'email-filter'
  | 'email-template';

// ============================================
// Node Types Registry
// ============================================

export interface NodeTypeDefinition {
  type: string;
  name: string;
  description: string;
  category: 'logic' | 'action' | 'trigger';
  config_schema: Record<string, any>;
  input_schema: Record<string, any>;
  output_schema: Record<string, any>;
}

// ============================================
// Workflow Execution
// ============================================

export interface WorkflowExecution {
  id: string;
  workflow_id: string;
  user_id: string;
  status: ExecutionStatus;
  input_data: Record<string, any> | null;
  output_data: Record<string, any> | null;
  error_message: string | null;
  started_at: string;
  completed_at: string | null;
  duration_ms: number | null;
  trigger_type: TriggerType | null;
  logs?: ExecutionLog[];
}

export interface ExecutionLog {
  id: string;
  execution_id: string;
  node_id: string;
  node_type: string;
  status: 'running' | 'completed' | 'failed' | 'skipped';
  input_data: Record<string, any> | null;
  output_data: Record<string, any> | null;
  error_message: string | null;
  started_at: string;
  completed_at: string | null;
  duration_ms: number | null;
  retry_count: number;
}

export type ExecutionStatus = 'running' | 'completed' | 'failed';
export type TriggerType = 'manual' | 'schedule' | 'email' | 'webhook';

// ============================================
// Workflow Validation
// ============================================

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
}

export interface ValidationError {
  nodeId?: string;
  type: string;
  message: string;
}

export interface ValidationWarning {
  nodeId?: string;
  type: string;
  message: string;
}

// ============================================
// Triggers
// ============================================

export interface TriggerConfig {
  id: string;
  workflow_id: string;
  trigger_type: TriggerType;
  config: CronTriggerConfig | EmailTriggerConfig | WebhookTriggerConfig;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface CronTriggerConfig {
  cron_expression: string;
  timezone?: string;
  input_data?: Record<string, any>;
}

export interface EmailTriggerConfig {
  email_account_id: string;
  folder: string;
  filter_rules: EmailFilterRule[];
  polling_interval_minutes: number;
  mark_as_read?: boolean;
}

export interface EmailFilterRule {
  field: 'from' | 'to' | 'subject' | 'body' | 'date';
  operator: 'equals' | 'contains' | 'starts_with' | 'ends_with' | 'regex';
  value: string;
}

export interface WebhookTriggerConfig {
  webhook_url?: string; // Generated by backend
  authentication?: {
    type: 'api_key' | 'signature';
    key?: string;
    secret?: string;
  };
}

// ============================================
// Email Accounts
// ============================================

export interface EmailAccount {
  id: string;
  user_id: string;
  name: string;
  email_address: string;
  provider: EmailProvider;
  auth_type: 'imap-smtp' | 'oauth2';
  config: EmailAccountConfig; // Redacted (passwords hidden)
  is_active: boolean;
  last_sync_at: string | null;
  last_error: string | null;
  created_at: string;
  updated_at: string;
}

export type EmailProvider = 'imap' | 'pop3' | 'smtp' | 'gmail' | 'outlook';

export interface EmailAccountConfig {
  // IMAP/SMTP
  username?: string;
  password?: string; // Will be "***" in responses
  host?: string;
  port?: number;
  secure?: boolean;
  // OAuth2
  clientId?: string;
  clientSecret?: string; // Will be "***" in responses
  accessToken?: string; // Will be "***" in responses
  refreshToken?: string; // Will be "***" in responses
  expiresAt?: string;
  scopes?: string[];
}

// ============================================
// Email Templates
// ============================================

export interface EmailTemplate {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  subject: string;
  body: string;
  format: 'text' | 'html' | 'both';
  variables: string[];
  tags: string[];
  usage_count: number;
  last_used_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface TemplatePreview {
  subject: string;
  body_html: string;
  body_text: string;
  variables_used: string[];
}

// ============================================
// Usage & Rate Limiting
// ============================================

export interface UsageStats {
  user_id: string;
  quota_tier: QuotaTier;
  current_usage: CurrentUsage;
  limits: UsageLimits;
  reset_times: ResetTimes;
}

export interface CurrentUsage {
  ai_calls_this_minute: number;
  emails_sent_this_hour: number;
  workflow_executions_today: number;
}

export interface UsageLimits {
  ai_calls_per_minute: number;
  emails_per_hour: number;
  workflow_executions_per_day: number;
}

export interface ResetTimes {
  ai_calls_reset_at: string;
  emails_reset_at: string;
  workflow_executions_reset_at: string;
}

export type QuotaTier = 'basic' | 'pro' | 'enterprise';

// ============================================
// Workflow Import/Export
// ============================================

export interface WorkflowExport {
  version: string;
  exported_at: string;
  workflows: Workflow[];
}

export interface WorkflowImportResult {
  imported: number;
  failed: number;
  workflows: ImportedWorkflow[];
  errors: ImportError[];
}

export interface ImportedWorkflow {
  original_id: string;
  new_id: string;
  name: string;
  status: 'success' | 'failed';
}

export interface ImportError {
  workflow_name: string;
  error: string;
}

// ============================================
// API Service Class
// ============================================

export class WorkflowAPI {
  private baseUrl: string;

  constructor(baseUrl: string = 'http://localhost:3000') {
    this.baseUrl = baseUrl;
  }

  private getHeaders(): HeadersInit {
    const token = typeof window !== 'undefined' 
      ? localStorage.getItem('access_token') 
      : null;
    
    return {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json'
    };
  }

  private async request<T>(
    endpoint: string,
    options?: RequestInit
  ): Promise<T> {
    const response = await fetch(`${this.baseUrl}${endpoint}`, {
      ...options,
      headers: {
        ...this.getHeaders(),
        ...options?.headers
      }
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || error.message || 'API request failed');
    }

    const json = await response.json();
    return json.data || json;
  }

  // ============================================
  // Workflow Management
  // ============================================

  async listWorkflows(): Promise<Workflow[]> {
    return this.request<Workflow[]>('/api/workflows');
  }

  async getWorkflow(id: string): Promise<Workflow> {
    return this.request<Workflow>(`/api/workflows/${id}`);
  }

  async createWorkflow(data: {
    name: string;
    description?: string;
    nodes: WorkflowNode[];
    edges: WorkflowEdge[];
  }): Promise<Workflow> {
    return this.request<Workflow>('/api/workflows', {
      method: 'POST',
      body: JSON.stringify(data)
    });
  }

  async updateWorkflow(
    id: string,
    data: Partial<Workflow>
  ): Promise<Workflow> {
    return this.request<Workflow>(`/api/workflows/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(data)
    });
  }

  async deleteWorkflow(id: string): Promise<void> {
    await this.request(`/api/workflows/${id}`, {
      method: 'DELETE'
    });
  }

  // ============================================
  // Workflow Execution
  // ============================================

  async executeWorkflow(
    id: string,
    input?: Record<string, any>
  ): Promise<{ executionId: string }> {
    return this.request(`/api/workflows/${id}/execute`, {
      method: 'POST',
      body: JSON.stringify({ input })
    });
  }

  async validateWorkflow(id: string): Promise<ValidationResult> {
    return this.request<ValidationResult>(`/api/workflows/${id}/validate`);
  }

  async getExecution(id: string): Promise<WorkflowExecution> {
    return this.request<WorkflowExecution>(`/api/executions/${id}`);
  }

  async listExecutions(params?: {
    workflow_id?: string;
    status?: ExecutionStatus;
    limit?: number;
    offset?: number;
  }): Promise<WorkflowExecution[]> {
    const query = new URLSearchParams(params as any).toString();
    return this.request<WorkflowExecution[]>(`/api/executions?${query}`);
  }

  // ============================================
  // Triggers
  // ============================================

  async listTriggers(workflowId: string): Promise<TriggerConfig[]> {
    return this.request<TriggerConfig[]>(
      `/api/workflows/${workflowId}/triggers`
    );
  }

  async createTrigger(
    workflowId: string,
    data: {
      trigger_type: TriggerType;
      config: any;
      is_active?: boolean;
    }
  ): Promise<TriggerConfig> {
    return this.request<TriggerConfig>(
      `/api/workflows/${workflowId}/triggers`,
      {
        method: 'POST',
        body: JSON.stringify(data)
      }
    );
  }

  async updateTrigger(
    workflowId: string,
    triggerId: string,
    data: Partial<TriggerConfig>
  ): Promise<TriggerConfig> {
    return this.request<TriggerConfig>(
      `/api/workflows/${workflowId}/triggers/${triggerId}`,
      {
        method: 'PATCH',
        body: JSON.stringify(data)
      }
    );
  }

  async deleteTrigger(workflowId: string, triggerId: string): Promise<void> {
    await this.request(`/api/workflows/${workflowId}/triggers/${triggerId}`, {
      method: 'DELETE'
    });
  }

  // ============================================
  // Node Types
  // ============================================

  async getNodeTypes(): Promise<NodeTypeDefinition[]> {
    return this.request<NodeTypeDefinition[]>('/api/node-types');
  }

  // ============================================
  // Email Accounts
  // ============================================

  async listEmailAccounts(): Promise<EmailAccount[]> {
    return this.request<EmailAccount[]>('/api/email/accounts');
  }

  async getEmailAccount(id: string): Promise<EmailAccount> {
    return this.request<EmailAccount>(`/api/email/accounts/${id}`);
  }

  async createEmailAccount(data: {
    name: string;
    email_address: string;
    provider: EmailProvider;
    auth_type: 'imap-smtp' | 'oauth2';
    config: EmailAccountConfig;
  }): Promise<EmailAccount> {
    return this.request<EmailAccount>('/api/email/accounts', {
      method: 'POST',
      body: JSON.stringify(data)
    });
  }

  async updateEmailAccount(
    id: string,
    data: Partial<EmailAccount>
  ): Promise<EmailAccount> {
    return this.request<EmailAccount>(`/api/email/accounts/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(data)
    });
  }

  async deleteEmailAccount(id: string): Promise<void> {
    await this.request(`/api/email/accounts/${id}`, {
      method: 'DELETE'
    });
  }

  async validateEmailAccount(
    id: string
  ): Promise<{ success: boolean; message: string }> {
    return this.request(`/api/email/accounts/${id}/validate`, {
      method: 'POST'
    });
  }

  // ============================================
  // Email Templates
  // ============================================

  async listEmailTemplates(): Promise<EmailTemplate[]> {
    return this.request<EmailTemplate[]>('/api/email/templates');
  }

  async getEmailTemplate(id: string): Promise<EmailTemplate> {
    return this.request<EmailTemplate>(`/api/email/templates/${id}`);
  }

  async createEmailTemplate(data: {
    name: string;
    description?: string;
    subject: string;
    body: string;
    format?: 'text' | 'html' | 'both';
    tags?: string[];
  }): Promise<EmailTemplate> {
    return this.request<EmailTemplate>('/api/email/templates', {
      method: 'POST',
      body: JSON.stringify(data)
    });
  }

  async updateEmailTemplate(
    id: string,
    data: Partial<EmailTemplate>
  ): Promise<EmailTemplate> {
    return this.request<EmailTemplate>(`/api/email/templates/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(data)
    });
  }

  async deleteEmailTemplate(id: string): Promise<void> {
    await this.request(`/api/email/templates/${id}`, {
      method: 'DELETE'
    });
  }

  async previewEmailTemplate(
    id: string,
    data: Record<string, any>
  ): Promise<TemplatePreview> {
    return this.request<TemplatePreview>(
      `/api/email/templates/${id}/preview`,
      {
        method: 'POST',
        body: JSON.stringify({ data })
      }
    );
  }

  // ============================================
  // Usage & Rate Limiting
  // ============================================

  async getUsageStats(): Promise<UsageStats> {
    return this.request<UsageStats>('/api/usage');
  }

  // ============================================
  // Import/Export
  // ============================================

  async exportWorkflow(id: string): Promise<WorkflowExport> {
    return this.request<WorkflowExport>(`/api/workflows/${id}/export`);
  }

  async exportWorkflows(ids: string[]): Promise<WorkflowExport> {
    const query = ids.map(id => `ids=${id}`).join('&');
    return this.request<WorkflowExport>(`/api/workflows/export?${query}`);
  }

  async importWorkflows(data: WorkflowExport): Promise<WorkflowImportResult> {
    return this.request<WorkflowImportResult>('/api/workflows/import', {
      method: 'POST',
      body: JSON.stringify(data)
    });
  }
}

// Export singleton instance
export const workflowApi = new WorkflowAPI();

// ============================================
// Usage Examples
// ============================================

/**
 * Example 1: Create and execute a workflow
 * 
 * const workflow = await workflowApi.createWorkflow({
 *   name: 'My First Workflow',
 *   description: 'Send email when condition is met',
 *   nodes: [
 *     {
 *       id: 'node-1',
 *       type: 'if-else',
 *       config: {
 *         condition: '{{input.value}} > 10'
 *       }
 *     },
 *     {
 *       id: 'node-2',
 *       type: 'send-email',
 *       config: {
 *         to: ['user@example.com'],
 *         subject: 'Alert',
 *         body: { text: 'Value exceeded threshold' }
 *       }
 *     }
 *   ],
 *   edges: [
 *     {
 *       id: 'edge-1',
 *       source: 'node-1',
 *       target: 'node-2',
 *       sourceHandle: 'true'
 *     }
 *   ]
 * });
 * 
 * const { executionId } = await workflowApi.executeWorkflow(workflow.id, {
 *   value: 15
 * });
 * 
 * const execution = await workflowApi.getExecution(executionId);
 * console.log(execution.status);
 */

/**
 * Example 2: Create a schedule trigger
 * 
 * const trigger = await workflowApi.createTrigger(workflowId, {
 *   trigger_type: 'schedule',
 *   config: {
 *     cron_expression: '0 9 * * *', // Every day at 9 AM
 *     timezone: 'Asia/Ho_Chi_Minh',
 *     input_data: { source: 'scheduled' }
 *   },
 *   is_active: true
 * });
 */

/**
 * Example 3: Create email account and template
 * 
 * const emailAccount = await workflowApi.createEmailAccount({
 *   name: 'My Gmail',
 *   email_address: 'user@gmail.com',
 *   provider: 'gmail',
 *   auth_type: 'oauth2',
 *   config: {
 *     clientId: 'your-client-id',
 *     clientSecret: 'your-client-secret',
 *     accessToken: 'your-access-token',
 *     refreshToken: 'your-refresh-token'
 *   }
 * });
 * 
 * const template = await workflowApi.createEmailTemplate({
 *   name: 'Welcome Email',
 *   subject: 'Welcome {{name}}!',
 *   body: '<h1>Hello {{name}}</h1><p>Welcome to our platform!</p>',
 *   format: 'html',
 *   tags: ['welcome', 'onboarding']
 * });
 * 
 * const preview = await workflowApi.previewEmailTemplate(template.id, {
 *   name: 'John Doe'
 * });
 */

/**
 * Example 4: Monitor workflow execution
 * 
 * const { executionId } = await workflowApi.executeWorkflow(workflowId);
 * 
 * // Poll for completion
 * let execution;
 * do {
 *   await new Promise(resolve => setTimeout(resolve, 1000));
 *   execution = await workflowApi.getExecution(executionId);
 * } while (execution.status === 'running');
 * 
 * if (execution.status === 'completed') {
 *   console.log('Success!', execution.output_data);
 * } else {
 *   console.error('Failed:', execution.error_message);
 * }
 */

/**
 * Example 5: Check usage and rate limits
 * 
 * const usage = await workflowApi.getUsageStats();
 * 
 * console.log(`AI calls: ${usage.current_usage.ai_calls_this_minute}/${usage.limits.ai_calls_per_minute}`);
 * console.log(`Emails sent: ${usage.current_usage.emails_sent_this_hour}/${usage.limits.emails_per_hour}`);
 * console.log(`Executions: ${usage.current_usage.workflow_executions_today}/${usage.limits.workflow_executions_per_day}`);
 */
